#!/bin/bash

bin="$(readlink -f "$(dirname "$0")" )"

i=$( "$bin"/freshen | tail -1 )
j=$( "$bin"/freshen.droplist | tail -1 )

i=$(( i + j ))

if [ $i -lt 1 -a "$1" = --force ]
then
	i=1
fi

if [ $i -gt 0 ]
then
	echo $i countries were freshened
	echo clearing iptables of country data
	"$bin"/clear-country-kill-list
	echo optimizing and loading new country data
	"$bin"/block-countries
fi
